dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
  - onchain-id/solidity@2.2.1
  - TokenySolutions/T-REX@4.1.3
compiler:
  solc:
    version: 0.8.17
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3'
      - '@onchain-id/solidity=onchain-id/solidity@2.2.1'
      - '@T-REX=TokenySolutions/T-REX@4.1.3'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}