dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
  - onchain-id/solidity@2.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3'
      - '@onchain-id/solidity=onchain-id/solidity@2.2.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}